# Generated by Django 2.1.7 on 2019-05-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean1', models.CharField(max_length=200)),
                ('mean2', models.CharField(max_length=200)),
                ('select', models.PositiveIntegerField()),
                ('picture', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Taro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('num', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
