# Generated by Django 2.1.7 on 2019-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_card_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='score',
            new_name='score1',
        ),
        migrations.AddField(
            model_name='card',
            name='score2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
