# Generated by Django 2.1.7 on 2019-05-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190524_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
